site_name: COMUNDA Documentation
site_description: User documentation for the COMUNDA portal
theme:
    name: readthedocs
    custom_dir: readthedocs_custom
site_dir: '_site'
extra_css: [css/extra.css]

nav:
- Overview:
  - Welcome to COMUNDA: index.md
  - Opening Account: account.md
- Interacting With Datasets:
  - Searching, viewing and rating: dataset.md
  - Requesting Datasets: request.md
  - Updating Labels: labels.md
  - Contributing Datasets: contribute.md
- Help:
  - Support: support.md

markdown_extensions:
    - attr_list
    - toc:
        permalink: 
    - admonition: